### ISSUE TITLE
Should expose module.Store so that other modules can extend easier

### ISSUE THREAD

**Issue by meyer9** [meyer9/micro-session#1]
```
TypeError: Cannot read property 'Store' of undefined
    at module.exports (/home/meyer9/development/upfunc/node_modules/connect-mongo/src/index.js:57:50)
    at Module../pages/api/connect.ts (/home/meyer9/development/upfunc/.next/server/static/development/pages/api/connect.js:111:74)
    at __webpack_require__ (/home/meyer9/development/upfunc/.next/server/static/development/pages/api/connect.js:23:31)
    at Object.3 (/home/meyer9/development/upfunc/.next/server/static/development/pages/api/connect.js:139:18)
    at __webpack_require__ (/home/meyer9/development/upfunc/.next/server/static/development/pages/api/connect.js:23:31)
    at /home/meyer9/development/upfunc/.next/server/static/development/pages/api/connect.js:91:18
    at Object.<anonymous> (/home/meyer9/development/upfunc/.next/server/static/development/pages/api/connect.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at DevServer.handleApiRequest (/home/meyer9/development/upfunc/node_modules/next/dist/next-server/server/next-server.js:239:76)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Related express code: https://github.com/expressjs/session/blob/master/index.js#L45

Related connect-mongo code: https://github.com/jdesboeufs/connect-mongo/blob/master/src/index.js#L57

**Comment by meyer9** [comment]
Fixed in v2.0.0
